2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Configure stats pid to 11720
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Loading settings from C:\Users\avs20\.config\wandb\settings
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Loading settings from c:\Users\avs20\Documents\GitHub\ViT_facemap\ResNet50\wandb\settings
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\avs20\Documents\GitHub\ViT_facemap\ResNet50\wandb\run-20241007_115153-xhks8htm\logs\debug.log
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\avs20\Documents\GitHub\ViT_facemap\ResNet50\wandb\run-20241007_115153-xhks8htm\logs\debug-internal.log
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_init.py:init():607] calling init triggers
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_init.py:init():632] re-initializing run, found existing run on stack: m3rn2n65
2024-10-07 11:51:53,784 INFO    MainThread:11720 [wandb_run.py:_finish():2160] finishing run anna-stuckert-university-of-st-andrews/Facemap_ResNet/m3rn2n65
2024-10-07 11:51:54,109 INFO    MainThread:11720 [jupyter.py:save_history():444] not saving jupyter history
2024-10-07 11:51:54,109 INFO    MainThread:11720 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-10-07 11:51:54,109 INFO    MainThread:11720 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-10-07 11:51:54,109 INFO    MainThread:11720 [wandb_run.py:_atexit_cleanup():2424] got exitcode: 0
2024-10-07 11:51:54,110 INFO    MainThread:11720 [wandb_run.py:_restore():2406] restore
2024-10-07 11:51:54,110 INFO    MainThread:11720 [wandb_run.py:_restore():2412] restore done
2024-10-07 11:51:54,110 INFO    MainThread:11720 [wandb_run.py:_on_finish():2677] communicating current version
2024-10-07 11:51:54,479 INFO    MainThread:11720 [wandb_run.py:_on_finish():2686] got version response upgrade_message: "wandb version 0.18.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-10-07 11:51:59,302 WARNING MainThread:11720 [wandb_init.py:init():1232] interrupted
Traceback (most recent call last):
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_init.py", line 1228, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_init.py", line 642, in init
    latest_run.finish()
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 452, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2153, in finish
    return self._finish(exit_code, quiet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2187, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2436, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2699, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avs20\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
